### ISSUE TITLE
Unexpected behaviour in `findap` with NaN in input

### ISSUE THREAD

**Issue by morbult** [twmacro/pyyeti#39]
Hi Tim,

I noticed this:

```python
>>> from pyyeti import cyclecount
>>> import numpy as np
>>> tf = cyclecount.findap(np.array([1, 2, 3, 4, 4, -2, -2, 0]))
>>> np.nonzero(tf)[0]
array([0, 3, 5, 7])
>>> tf = cyclecount.findap(np.array([1, 2, 3, 4, 4, -2, -2, 0, np.nan]))
>>> np.nonzero(tf)[0]
array([0])
```

The second call to `findap` gives just a single True at the 0th index. It seems this is the case if there is at least 1 NaN somewhere in the input array.

This was unexpected to me since it (incorrectly) says there are no peaks in the data, as if the input was just a run of constant values.

Maybe this behaviour is intended. If so, I think it should be written in the docstring.

However, I would have expected that either NaN values were ignored and you get the same result as if NaNs were filled with previous non-NaN values, or an error was raised notifying that peaks can not be found with NaNs in the array. If choosing to ignore NaNs, maybe a RuntimeWarning would be good, similar to the one from numpy if you do `np.array(0) / 0`.

I tested this on Python 3.13, pyyeti 1.4.3.6, with and without the C extension, with and without numba.

**Comment by twmacro** [comment]
Thank you @morbult for the report! I'll take a look at this and get back to you. :)

(I appreciate the excellent little example too!)

**Comment by twmacro** [comment]
Hi @morbult,

I believe I have fixed this issue with version 1.4.3.7. Let me know if you concur. :)

Regards,
Tim

**Comment by morbult** [comment]
Great solution! I like that NaNs are ignored by default but you still have the option to get the performance gain by setting nan_check=False. Sorry for the late reply.

**Comment by twmacro** [comment]
Thanks for the feedback, @morbult! :)
